import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Sidebar } from "@/partials/Sidebar";
import { StickyMobileNavbar } from "@/partials/StickyMobileNavbar";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Magnetar Finance | MetaDEX on EVM",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <div className="flex flex-col md:flex-row min-h-screen min-w-screen justify-center items-start gap-0 overflow-y-auto overflow-x-hidden">
          <div className="hidden md:block w-[15%]">
            <Sidebar />
          </div>
          <div className="w-screen md:w-[85%]">{children}</div>
          <div className="md:hidden w-full px-3 pb-5 fixed bottom-0 left-0">
            <StickyMobileNavbar />
          </div>
        </div>
      </body>
    </html>
  );
}
